### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by grahampugh** [dibollinger/CookieBlock#4]
Not really an issue, more of a request - are there any plans to offer a Safari version? That would help for Apple devices (computers and mobile devices).

**Comment by grahampugh** [comment]
Thanks, that's interessting, but that's not my question. The question was, is this project planning to offer a Safari extension (via the App Store)? Since Safari is the #2 browser in use (behind Chrome, far ahead of Firefox, Edge and Opera), it would be a shame to limit coverage to only a subset of consumer devices.

**Comment by Bender250** [comment]
We tried this, but the problem is that Safari does not allow any of 2 way how we can collect cookie changes.

* [cookies.onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged)
* [change event of cookie store API](https://developer.mozilla.org/en-US/docs/Web/API/Cookie_Store_API)

This is needed [here](https://github.com/dibollinger/CookieBlock/blob/main/src/background/cookieblock_background.js#L784).  Without that, CookieBlock in Safari would be just a bit smarter cookie remover when the user triggers the action. But even our features extraction is harmed, so with lower accuracy than other browsers.

If you know some other way to solve this, let us please know!
